#!/bin/bash
# fgt remote-head BRANCH [REPO]

branch="$1"
if [ $# -gt 1 ]; then
    repo="$($FGT-abspath $2)"
else
    repo="$($FGT-git-remote)"
fi

git ls-remote "$repo" refs/heads/"$branch" | cut -f1 | head -1
