#!/bin/bash

die() {
    echo >&2 "$@"
    exit 1
}

branch="$1"
if [ $# -gt 1 ]; then
    repo="$($FGT-abspath $2)"
else
    repo="$($FGT-git-remote)"
fi
parent="$($FGT-remote-head "$@")"
test -n "$parent" || die "Couldn't find current remote head..."

commitmsg="$(mktemp)"
pack="$(mktemp)"
trap "rm -f $commitmsg $pack" exit

echo >"$commitmsg" "*** no commit message ***"
vim "$commitmsg" || die "editor returned 1"
author_email="$(whoami) <$(whoami)@$(hostname)>"

$FGT-ls-files -print0 |
$FGT-make-commit-pack "refs/heads/$branch" "$author_email" "$commitmsg" "$parent" |
($FGT-rsh "$repo" git receive-pack . >/dev/null)
