#!/bin/bash
# fgt checkout/co BRANCH [REPO] [DIR]

tree="$1"
if [ $# -gt 1 -a -d "$2" ]; then
    repo="$($FGT-abspath $2)"
elif [ $# -gt 1 ]; then
    repo="$2"
else
    repo="$($FGT-git-remote)"
fi
target="${3-.}"

proto=$($FGT-detect-proto "$repo")

# FIXME Doesn't remove files, and prints every file. We'd like to show
# something like A/M/D [file], and also sync the deletion.
$FGT-checkout-$proto "$repo" "$tree" |
tar -zxv --show-transformed-names --transform 's|^[^/]*|'"$target"'|'

# Could actually save the branch too
echo "$repo" > "$target/.fgt"
